#include <stdio.h>
#include <math.h>

#include "elk.h"
#include "magpie.h"
#include "coyote.h"
#include "packrat.h"

#include "sonde-anal.c"

/* Disable some warnings that will be generated by RayLib. I don't own this lib and can do nothing about it. */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-result"

#include "raylib.h"
#define RAYGUI_IMPLEMENTATION
#include "raygui.h"
#include "style_amber.h" /* RayGui Amber style */
#include "style_dark.h"  /* RayGui Dark style  */

#pragma GCC diagnostic pop

#define GRAPHICS_DEBUG 1

typedef struct
{
    /* Window Data */
    i32 screenWidth;
    i32 screenHeight;

    /* Text Data */
    i32 fontSize;
} Layout;

typedef struct
{
    RenderTexture left_pane;
    RenderTexture right_pane;
    Rectangle splitScreenRect;
    Font font;
    f32 textHeight;

    /* Buttons */
    f32 buttonRowY;
    f32 buttonHeight;

    /* Button Row */
    f32 openButtonX;
    f32 openButtonWidth;
    f32 saveImageButtonX;
    f32 saveImageButtonWidth;
    f32 firstButtonX;
    f32 firstButtonWidth;
    f32 previousButtonX;
    f32 previousButtonWidth;
    f32 nextButtonX;
    f32 nextButtonWidth;
    f32 lastButtonX;
    f32 lastButtonWidth;
} RendererState;

typedef struct
{
    u32 backgroundColorIdx;
} DataModel;

typedef struct 
{
    Layout layout;
    RendererState renderer;
    DataModel data_model;
} ProgramState;

void process_input(ProgramState *state);     /* Captures input and processes it before any changes to the program state  */
void update_gui_state(ProgramState *state);  /* Handles window resizes and changes to other semi-permanent program state */
void draw_left_pane(ProgramState *state);
void draw_right_pane(ProgramState *state);
void draw_button_bar(ProgramState *state);


int
main(void)
{
    /* Initialization -----------------------------------------------------------------------------------------------------*/
    i32 const screenWidth = 800;
    i32 const screenHeight = 450;

    SetConfigFlags(FLAG_WINDOW_RESIZABLE | FLAG_WINDOW_HIGHDPI);
    InitWindow(screenWidth, screenHeight, "Sonde2");

    ProgramState state = {0};
    if(0) GuiLoadStyleAmber();
    else GuiLoadStyleDark();
    update_gui_state(&state);

    SetTargetFPS(60);

    /* Main Loop ----------------------------------------------------------------------------------------------------------*/
    while(!WindowShouldClose())
    {
        /* Update ---------------------------------------------------------------------------------------------------------*/
        process_input(&state);
        update_gui_state(&state);

        /* Draw -----------------------------------------------------------------------------------------------------------*/
        draw_left_pane(&state);
        draw_right_pane(&state);

        /* Put everything on the window -----------------------------------------------------------------------------------*/
        BeginDrawing();

        {
#if GRAPHICS_DEBUG
            ClearBackground(YELLOW);
#else
            ClearBackground(BLACK);
#endif

            /* Build Top Row of Buttons */
            draw_button_bar(&state);

            /* Draw in the left pane */
            DrawTextureRec(
                    state.renderer.left_pane.texture,
                    state.renderer.splitScreenRect,
                    (Vector2){ 0.0f, state.renderer.buttonHeight },
                    WHITE);

            /* Draw in the right pane */
            DrawTextureRec(state.renderer.right_pane.texture,
                    state.renderer.splitScreenRect,
                    (Vector2){ state.layout.screenWidth / 2.0f,
                    state.renderer.buttonHeight },
                    WHITE);
        }

        EndDrawing();
    }

    UnloadFont(state.renderer.font);
    CloseWindow();

    return 0;
}

void 
process_input(ProgramState *state)
{
}

void
update_gui_state(ProgramState *state)
{
#define BUTTON_HORIZONTAL_PADDING 5.0f
    /* One time set up based off zero initialized struct */
    if(!state->renderer.font.baseSize)
    {
        /* Set up font */
        state->layout.fontSize  = state->layout.fontSize ? state->layout.fontSize : 18;
        state->renderer.font = LoadFontEx("resources/FiraSans-Bold.otf", state->layout.fontSize, 0, 0);
        SetTextLineSpacing(3 * state->layout.fontSize / 4);
        GuiSetFont(state->renderer.font);
        state->renderer.textHeight = MeasureTextEx(state->renderer.font, "gÅ", (f32)state->layout.fontSize, (f32)(state->layout.fontSize / 4)).y;

        /* Layout the top row of buttons. */
        state->renderer.buttonHeight = 1.4f * state->renderer.textHeight;
        state->renderer.buttonRowY = 0.0f;

        state->renderer.openButtonWidth      = (f32)MeasureText("#1#Open",         state->layout.fontSize);
        state->renderer.saveImageButtonWidth = (f32)MeasureText("#184#Save Image", state->layout.fontSize);
        state->renderer.firstButtonWidth     = (f32)MeasureText("#129#First",      state->layout.fontSize);
        state->renderer.previousButtonWidth  = (f32)MeasureText("#118#Previous",   state->layout.fontSize);
        state->renderer.nextButtonWidth      = (f32)MeasureText("#119#PNext",      state->layout.fontSize);
        state->renderer.lastButtonWidth      = (f32)MeasureText("#134#Last",       state->layout.fontSize);

        /* Layout buttons that flow from the left. */
        state->renderer.openButtonX = BUTTON_HORIZONTAL_PADDING;
        state->renderer.saveImageButtonX = state->renderer.openButtonX + state->renderer.openButtonWidth + BUTTON_HORIZONTAL_PADDING;

        /* Set some GUI styles and defaults */
        GuiSetStyle(DEFAULT, TEXT_SIZE, state->layout.fontSize);
        GuiSetStyle(BUTTON, BORDER_WIDTH, 0);
    }

    /* Handle window resizes */
    i32 const screenWidth = GetScreenWidth();
    i32 const screenHeight = GetScreenHeight();

    if(screenWidth != state->layout.screenWidth || screenHeight != state->layout.screenHeight)
    {
        /* Calculate the minimum allowable width to hold all the buttons */
        f32 minWidth = state->renderer.openButtonWidth
            + state->renderer.saveImageButtonWidth
            + state->renderer.firstButtonWidth
            + state->renderer.previousButtonWidth
            + state->renderer.nextButtonWidth
            + state->renderer.lastButtonWidth
            + 5.0f * BUTTON_HORIZONTAL_PADDING;

        state->layout.screenWidth = screenWidth > minWidth ? screenWidth : minWidth;
        state->layout.screenHeight = screenHeight;
        UnloadRenderTexture(state->renderer.left_pane);
        UnloadRenderTexture(state->renderer.right_pane);

        state->renderer.left_pane = LoadRenderTexture(state->layout.screenWidth / 2, state->layout.screenHeight - state->renderer.buttonHeight);
        state->renderer.right_pane = LoadRenderTexture(state->layout.screenWidth / 2, state->layout.screenHeight - state->renderer.buttonHeight);
        state->renderer.splitScreenRect = (Rectangle){ 0.0f, 0.0f, (f32)state->renderer.left_pane.texture.width, (f32)-state->renderer.left_pane.texture.height };

        /* Layout buttons that are centered. */
        f32 screenWidth_f32 = (f32)state->layout.screenWidth;
        f32 centeredButtonsWidth =
            state->renderer.lastButtonWidth
            + state->renderer.nextButtonWidth 
            + state->renderer.previousButtonWidth 
            + state->renderer.firstButtonWidth 
            + 3.0f * BUTTON_HORIZONTAL_PADDING;

        f32 minCenteredButtonsX = state->renderer.saveImageButtonX + state->renderer.saveImageButtonWidth + BUTTON_HORIZONTAL_PADDING;

        state->renderer.firstButtonX = (screenWidth_f32 - centeredButtonsWidth) / 2.0f;
        if(state->renderer.firstButtonX < minCenteredButtonsX) { state->renderer.firstButtonX = minCenteredButtonsX; }

        state->renderer.previousButtonX = state->renderer.firstButtonX     + state->renderer.firstButtonWidth    + BUTTON_HORIZONTAL_PADDING;
        state->renderer.nextButtonX =     state->renderer.previousButtonX  + state->renderer.previousButtonWidth + BUTTON_HORIZONTAL_PADDING;
        state->renderer.lastButtonX =     state->renderer.nextButtonX      + state->renderer.nextButtonWidth     + BUTTON_HORIZONTAL_PADDING;
    }
#undef BUTTON_HORIZONTAL_PADDING
}

void 
draw_left_pane(ProgramState *state)
{
    RendererState *r = &state->renderer;
    RenderTexture *render_texture = &r->left_pane;
    Texture *texture = &render_texture->texture;
    i32 const width = texture->width;
    i32 const height = texture->height;

    BeginTextureMode(*render_texture);

    {
        ClearBackground(RAYWHITE);

#if GRAPHICS_DEBUG
        Rectangle lrect = {.x = 0, .y = 0, .width = width, .height = height };
        DrawRectangleLinesEx(lrect, 8.0, GREEN);
#endif
    }

    EndTextureMode();

}

void 
draw_right_pane(ProgramState *state)
{
    RendererState *r = &state->renderer;
    RenderTexture *render_texture = &r->right_pane;
    Texture *texture = &render_texture->texture;
    i32 const width = texture->width;
    i32 const height = texture->height;

    BeginTextureMode(*render_texture);

    {
        ClearBackground(RAYWHITE);

#if GRAPHICS_DEBUG
        Rectangle rrect = {.x = 0, .y = 0, .width = width, .height = height };
        DrawRectangleLinesEx(rrect, 8.0, PINK);
#endif
    }

    EndTextureMode();
}

void 
draw_button_bar(ProgramState *state)
{
    RendererState *r = &state->renderer;
    if(GuiButton((Rectangle){ .x = r->openButtonX, .y = r->buttonRowY, .width = r->openButtonWidth, .height = r->buttonHeight }, "#1#Open"))
    {
        // TODO: Handle File Open
        TraceLog(LOG_ERROR, "File open button not implemented yet!");
    }

    if(GuiButton((Rectangle){ .x = r->saveImageButtonX, .y = r->buttonRowY, .width = r->saveImageButtonWidth, .height = r->buttonHeight }, "#184#Save Image"))
    {
        // TODO: Handle Save Image 
        TraceLog(LOG_ERROR, "Save image button not implemented yet!");
    }

    if(GuiButton((Rectangle){ .x = r->firstButtonX, .y = r->buttonRowY, .width = r->firstButtonWidth, .height = r->buttonHeight }, "#129#First"))
    {
        // TODO: Handle First
        TraceLog(LOG_ERROR, "First button not implemented yet!");
    }

    if(GuiButton((Rectangle){ .x = r->previousButtonX, .y = r->buttonRowY, .width = r->previousButtonWidth, .height = r->buttonHeight }, "#118#Previous"))
    {
        // TODO: Handle Previous
        TraceLog(LOG_ERROR, "Previous button not implemented yet!");
    }

    if(GuiButton((Rectangle){ .x = r->nextButtonX, .y = r->buttonRowY, .width = r->nextButtonWidth, .height = r->buttonHeight }, "#119#Next"))
    {
        // TODO: Handle Next
        TraceLog(LOG_ERROR, "Next button not implemented yet!");
    }

    if(GuiButton((Rectangle){ .x = r->lastButtonX, .y = r->buttonRowY, .width = r->lastButtonWidth, .height = r->buttonHeight }, "#134#Last"))
    {
        // TODO: Handle Last
        TraceLog(LOG_ERROR, "Last button not implemented yet!");
    }

}

